package com.plantintelligence.backend.model;

import com.plantintelligence.backend.repository.UserRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for the {@link User} JPA entity and the Flyway migration
 * {@code V1__create_users_table.sql}.
 *
 * <h3>Infrastructure</h3>
 * <ul>
 *   <li>{@code @DataJpaTest} starts a minimal Spring context with only JPA
 *       components. No web layer, no full application context.</li>
 *   <li>{@code @AutoConfigureTestDatabase(replace = Replace.NONE)} prevents
 *       Spring Boot from substituting an auto-configured embedded database,
 *       allowing Flyway to run against our explicitly configured H2 instance.</li>
 *   <li>{@code @ActiveProfiles("test")} loads {@code application-test.properties}
 *       which configures an H2 in-memory database in PostgreSQL compatibility
 *       mode. <strong>No Supabase/network connection is required.</strong></li>
 *   <li>Flyway runs the production migration script against H2 on startup,
 *       then Hibernate validates the entity mappings against the created schema.</li>
 * </ul>
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
class UserEntityTest {

    @Autowired
    private UserRepository userRepository;

    // -------------------------------------------------------------------------
    // Helper
    // -------------------------------------------------------------------------

    private User buildUser(String username, String email) {
        return new User(
                username,
                email,
                "$2a$10$exampleHashedPassword",   // simulated BCrypt hash, not a real secret
                UserRole.USER
        );
    }

    // -------------------------------------------------------------------------
    // 1. Entity mapping — Flyway creates the schema; Hibernate validates it
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("Flyway migration creates the users table and JPA entity is correctly mapped")
    void entityMapping_flywayRunsAndEntityIsRecognised() {
        // If Flyway failed or the entity mapping is wrong, the Spring context
        // would not start at all and this test would fail with a startup error.
        assertThat(userRepository).isNotNull();
    }

    // -------------------------------------------------------------------------
    // 2. Persistence — save and retrieve
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("Saving a User generates an ID and all fields are persisted correctly")
    void persistence_saveAndRetrieveUser() {
        User user = buildUser("alice", "alice@example.com");
        user.setRole(UserRole.ADMIN);

        User saved = userRepository.save(user);

        // ID must have been auto-generated by the database
        assertThat(saved.getId()).isNotNull().isPositive();

        // Retrieve fresh from database to avoid returning the in-memory instance
        User retrieved = userRepository.findById(saved.getId()).orElseThrow();

        assertThat(retrieved.getUsername()).isEqualTo("alice");
        assertThat(retrieved.getEmail()).isEqualTo("alice@example.com");
        assertThat(retrieved.getPasswordHash()).isEqualTo("$2a$10$exampleHashedPassword");
        assertThat(retrieved.getRole()).isEqualTo(UserRole.ADMIN);
    }

    @Test
    @DisplayName("Role is stored as the enum name string, not an ordinal integer")
    void persistence_roleStoredAsString() {
        User user = buildUser("bob", "bob@example.com");
        // role defaults to UserRole.USER in buildUser()

        User saved = userRepository.save(user);
        User retrieved = userRepository.findById(saved.getId()).orElseThrow();

        // The enum value must round-trip correctly (string persistence)
        assertThat(retrieved.getRole()).isEqualTo(UserRole.USER);
    }

    // -------------------------------------------------------------------------
    // 3. Unique constraints
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("Duplicate username violates the unique constraint")
    void uniqueConstraint_duplicateUsernameIsRejected() {
        userRepository.save(buildUser("carol", "carol@example.com"));
        userRepository.flush(); // ensure the first INSERT is committed to H2

        User duplicate = buildUser("carol", "different@example.com");

        assertThatThrownBy(() -> {
            userRepository.saveAndFlush(duplicate);
        }).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    @DisplayName("Duplicate email violates the unique constraint")
    void uniqueConstraint_duplicateEmailIsRejected() {
        userRepository.save(buildUser("dave", "shared@example.com"));
        userRepository.flush();

        User duplicate = buildUser("differentuser", "shared@example.com");

        assertThatThrownBy(() -> {
            userRepository.saveAndFlush(duplicate);
        }).isInstanceOf(DataIntegrityViolationException.class);
    }

    // -------------------------------------------------------------------------
    // 4. NOT NULL constraints
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("Null username violates the NOT NULL constraint")
    void notNullConstraint_nullUsernameIsRejected() {
        User user = new User(null, "eve@example.com", "$2a$10$hash", UserRole.USER);

        assertThatThrownBy(() -> {
            userRepository.saveAndFlush(user);
        }).isInstanceOf(Exception.class); // DataIntegrityViolationException or ConstraintViolationException
    }

    @Test
    @DisplayName("Null email violates the NOT NULL constraint")
    void notNullConstraint_nullEmailIsRejected() {
        User user = new User("frank", null, "$2a$10$hash", UserRole.USER);

        assertThatThrownBy(() -> {
            userRepository.saveAndFlush(user);
        }).isInstanceOf(Exception.class);
    }

    @Test
    @DisplayName("Null passwordHash violates the NOT NULL constraint")
    void notNullConstraint_nullPasswordHashIsRejected() {
        User user = new User("grace", "grace@example.com", null, UserRole.USER);

        assertThatThrownBy(() -> {
            userRepository.saveAndFlush(user);
        }).isInstanceOf(Exception.class);
    }

    // -------------------------------------------------------------------------
    // 5. toString security — passwordHash must never appear in logs
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("toString() does not expose the password hash")
    void toStringSecurity_passwordHashIsNotExposed() {
        String sensitiveHash = "$2a$10$SENSITIVE_HASH_VALUE";
        User user = new User("heidi", "heidi@example.com", sensitiveHash, UserRole.USER);

        String output = user.toString();

        assertThat(output)
                .doesNotContain(sensitiveHash)
                .contains("heidi")
                .contains("heidi@example.com");
    }

    // -------------------------------------------------------------------------
    // 6. equals / hashCode — JPA identity strategy
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("Two persisted users with the same ID are equal")
    void equality_persistedUsersWithSameIdAreEqual() {
        User saved = userRepository.save(buildUser("ivan", "ivan@example.com"));

        User retrieved = userRepository.findById(saved.getId()).orElseThrow();

        assertThat(saved).isEqualTo(retrieved);
    }

    @Test
    @DisplayName("Two transient users are not equal to each other even if data matches")
    void equality_transientUsersAreNotEqual() {
        User a = buildUser("judy", "judy@example.com");
        User b = buildUser("judy", "judy@example.com");

        // Neither has been persisted — id is null for both
        assertThat(a).isNotEqualTo(b);
    }
}
