-- =============================================================================
-- Migration : V1__create_users_table.sql
-- Purpose   : Creates the initial `users` table for the PlantIntelligence
--             user management system.
--
-- Managed by Flyway — do NOT edit this file once it has been applied to any
-- database. Create a new versioned migration (V2__...) for any future changes.
-- =============================================================================

CREATE TABLE users (
    id            BIGSERIAL       NOT NULL,
    username      VARCHAR(50)     NOT NULL,
    email         VARCHAR(255)    NOT NULL,
    password_hash VARCHAR(255)    NOT NULL,
    role          VARCHAR(30)     NOT NULL,

    CONSTRAINT pk_users          PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE      (username),
    CONSTRAINT uq_users_email    UNIQUE      (email)
);
